[package]
name = "flashcards-client"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
flashcards_data = { path = "../flashcards_data" }
implicit-clone = "0.6.0"
